# Generated by Django 4.2.7 on 2023-12-28 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentHub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='downloadLink',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='resource',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
