# Generated by Django 4.2.7 on 2023-12-28 18:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('studentHub', '0002_resource_downloadlink_resource_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='likes',
            field=models.ManyToManyField(related_name='liked_resources', to=settings.AUTH_USER_MODEL),
        ),
    ]
