# Generated by Django 4.2.7 on 2023-12-28 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentHub', '0004_profile_birthday_profile_classroom_profile_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(default='profile_pics/default.jpg', upload_to='profile_pics/'),
        ),
    ]
