# Generated by Django 4.2.7 on 2023-12-28 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentHub', '0005_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.CharField(default='https://t4.ftcdn.net/jpg/00/64/67/27/360_F_64672736_U5kpdGs9keUll8CRQ3p3YaEv2M6qkVY5.jpg', max_length=1000),
        ),
    ]
