# Generated by Django 4.2.7 on 2023-12-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentHub', '0008_alter_profile_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='rater',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='resource',
        ),
        migrations.RemoveField(
            model_name='resource',
            name='num_ratings',
        ),
        migrations.DeleteModel(
            name='Notification',
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
